### ISSUE TITLE
What does the "data-o-ads-name" attribute do?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-ads#105]
The [docs site](https://financial-times.github.io/o-ads/docs/developer-guide/display) uses `data-o-ads-name="mpu"` as an example but doesn't mention what this does. The example is a bit confusing because it requests large ad sizes (like Leaderboard, SuperLeaderboard, Billboard), but the name is "mpu". What is this attribute for? Can I name it anything? Can I omit it?

**Comment by carlesandres** [comment]
Fixing here: https://github.com/Financial-Times/o-ads/pull/194
