### ISSUE TITLE
oAds.debug() throws an error when fluid ads are configured

### ISSUE THREAD

**Issue by antoligy** [Financial-Times/o-ads#208]
***Steps to Reproduce***
1. Define an ad-slotwith a size of "Fluid"
2. Run 'oAds.debug'

***Expected Result***
I should see my configuration output.

***Actual Result***
I receive an error message from a join: ```Uncaught TypeError: t.join is not a function
    at app.820388437c5de62476ed.js?4bc9:6
    at Array.map (<anonymous>)
    at i.<anonymous> (app.820388437c5de62476ed.js?4bc9:6)
    at app.820388437c5de62476ed.js?4bc9:6
    at Array.forEach (<anonymous>)
    at i.forEach (app.820388437c5de62476ed.js?4bc9:6)
    at i.debug (app.820388437c5de62476ed.js?4bc9:6)
    at i.YVfX.i.debug (app.820388437c5de62476ed.js?4bc9:6)
    at <anonymous>:1:14```

***Notes***
```json
{
  "gpt": {
    "network": "7049",
    "site": "NikkeiEnglish",
    "zone": null
  },
  "formats": {
    "Advertorial": {
      "sizes": "fluid"
    }
  }
}
```

**Comment by carlesandres** [comment]
Thanks @antoligy for reporting. We'll look into this.

**Comment by antoligy** [comment]
Hi, 

Sorry this is with 10.0.4.  I can try 10.2.0 early next week.

**Comment by alexflorisca** [comment]
Hi @antoligy, is this still a problem? I'm trying to debug it now - with version 10.2 it seems to work. With any version less than that, the `oAds` object is not exposed on the window object so I'm not sure how you're getting that error? Let me know if it's still an issue and what browser you're using, etc...

**Comment by antoligy** [comment]
Hey, have just checked this out in o-ads 10.2.0 and all is well now!
Thanks for looking into @alexflorisca
