### ISSUE TITLE
`data-o-ads-label="false"` doesn't act as expected

### ISSUE THREAD

**Issue by carlesandres** [Financial-Times/o-ads#283]
It's been reported that `data-o-ads-label="false"` still makes the label appear as set in this line of code: https://github.com/Financial-Times/o-ads/blob/4968033b1de75bd064bcc80fa8aa34cab55c57f3/src/js/slot.js#L189

**Comment by alexflorisca** [comment]
Can't replicate this and there hasn't been any problems since this was reported, so closing as no active development is happening on o-ads anymore.
