### ISSUE TITLE
Discussion points

### ISSUE THREAD

**Issue by oliverturner** [Financial-Times/o-ads#330]
There are a few ideas I'm interested in getting feedback on

## Architecture
I've mentioned moving towards a monorepo to a couple of you and it seems that it could be helpful... where do you think the boundaries lie?

## TypeScript
Potentially controversial! 

Personally I'm a big fan because it *really* helps when refactoring (and in fact just saved me from a really nasty but easy-to-make error), but I know that it's not for everyone and it can sometimes be a big dev overhead when you're just trying to get something working...

In the interest of transparency it's also worth noting that we can also get pretty far with typed JSDoc notation, but it starts to get limiting pretty quickly...

Any interest?

## Redundant polyfilling
`src/js/utils/index.js` contains a *lot* of polyfills for methods that are already covered by Page Kit, but may not be by other consumers... would it make sense to produce polyfilled and non-polyfilled versions?

## Updating dependencies
There are quite a number! Status on 2020-02-20
```
 Patch Update Backwards-compatible bug fixes.
 ◯ @financial-times/secret-squirrel devDep  2.12.4  ❯  2.12.5 
 ◯ browserstack-local devDep                1.4.0   ❯  1.4.5  
 ◯ start-server-and-test devDep             1.10.0  ❯  1.10.8 
  
 Minor Update New backwards-compatible features.
 ◯ @babel/core devDep                       7.5.4    ❯  7.8.4   
 ◯ @babel/preset-env devDep                 7.5.4    ❯  7.8.4   
 ◯ dotenv devDep                            8.0.0    ❯  8.2.0   
 ◯ geckodriver devDep                       1.16.2   ❯  1.19.1  
 ◯ genversion devDep                        2.1.1    ❯  2.2.0   
 ◯ jest-puppeteer devDep                    4.3.0    ❯  4.4.0   
 ◯ karma devDep                             4.2.0    ❯  4.4.1   
 ◯ karma-coverage-istanbul-reporter devDep  2.0.5    ❯  2.1.1   
 ◯ release-it devDep                        12.3.3   ❯  12.6.0  
 ◯ snyk devDep                              1.193.2  ❯  1.294.0 
 ◯ webpack devDep                           4.36.0   ❯  4.41.6  
  
 Major Update Potentially breaking API changes. Use caution.
 ◯ @cypress/webpack-preprocessor devDep  2.0.1   ❯  4.1.1   
 ◯ @testing-library/jest-dom devDep      4.1.0   ❯  5.1.1   
 ◯ babel-jest devDep                     24.8.0  ❯  25.1.0  
 ◯ cypress devDep                        3.4.0   ❯  4.0.2   
 ◯ eslint-plugin-jest devDep             22.9.0  ❯  23.7.0  
 ◯ fetch-mock devDep                     5.13.1  ❯  8.3.2   
 ◯ jest devDep                           24.8.0  ❯  25.1.0  
 ◯ karma-chrome-launcher devDep          0.2.3   ❯  3.1.0   
 ◯ karma-cli devDep                      0.1.2   ❯  2.0.0   
 ◯ karma-coverage devDep                 1.1.2   ❯  2.0.1   
 ◯ karma-qunit devDep                    0.1.9   ❯  4.0.0   
 ◯ karma-webpack devDep                  3.0.5   ❯  4.0.2   
 ◯ puppeteer devDep                      1.19.0  ❯  2.1.1   
 ◯ qunitjs devDep                        1.23.1  ❯  2.4.1  
```

I'd also like to think about which ones we can work towards eliminating... what are potential candidates?

## Consistent code style
I'd love to simplify our config: what do you all think about eliminating formatting rules from ESLint and relying on Prettier instead?

Eslint would still provide value in catching errors, but we'd only extend recommended plugins

**Comment by alevito** [comment]
Totally agree about the suggestions updating dependencies and getting rid of redundant polyfilling.

I also agree about simplifying - and potentially making less restricitve? - the code formatting rules.

Regarding moving to a monorepo, I would like a discussions of having a monorepo vs multiple repos during dev huddle. Maybe @oliverturner could lead this as he has experience working with monorepos - aka page-kit

Using TypeScript would be great and potentially improve the code readability - function prototypes would be better documented instead of relying on jsdoc. I would also consider using Flow as an alternative which is quite similar to TypeScript and can be added progressively to the codebase, and does not necessarily require the code to be transpiled: type definitions can be either included via comments or in code.

**Comment by alexflorisca** [comment]
Closing this as most point have been addressed. We have moved to a [monorepo](https://github.com/Financial-Times/advertising/) which has typescript and consistent style, have sorted a lot of the dependencies and are deprecating o-ads.
