### ISSUE TITLE
Version in package.json out of sync with tags

### ISSUE THREAD

**Issue by kornelski** [Financial-Times/o-ads#35]
Version tagged in git as 4.0.0 has v3 in package.json: 

https://github.com/Financial-Times/o-ads/blob/e49b305a2620df86754fdb85d5fe5ffe7727b807/package.json#L3

BTW: there's a nice [semver-sync](https://github.com/cimi/semver-sync) tool

**Comment by VladDubrovskis** [comment]
ooooh.. this has been out of date since version 3.0.1
Will patch this up
