### ISSUE TITLE
oAds.utils.arrayLikeToArray is not a function

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-ads#37]
v4.0.0 in the webapp:

```js
var advertsNodeList = oAds.utils.arrayLikeToArray(targetPane.node.querySelectorAll('.o-ads'));
```

> oAds.utils.arrayLikeToArray is not a function

**Comment by VladDubrovskis** [comment]
As this is a major release I think it's expected that some things might break?
This was meant to be an oAds only utility function (out code base is not too clear on public vs private methods)

**Comment by VladDubrovskis** [comment]
I think this relates to: https://github.com/Financial-Times/o-ads/issues/9

**Comment by VladDubrovskis** [comment]
#9

**Comment by pornel** [comment]
ok, we'll remove it
