### ISSUE TITLE
slot.responsiveCreative is no longer valid and therefore confusing

### ISSUE THREAD

**Issue by adgad** [Financial-Times/o-ads#59]
We set a flag called responsiveCreative if we get an event from o-ads-embed. This flag was intended to stop refreshing the slot - but given we don't use it and we've implemented it a different way, we should get rid of that code (or consolidate how we do it).

**Comment by alexflorisca** [comment]
Talked to @adgad about this and it looks like the `setResponsiveCreative` function is still being used so there is no need to delete. Closing this issue.
