### ISSUE TITLE
Can we put ads in aria-hidden containers

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-ads#7]
They wreck accessibility ![image](https://cloud.githubusercontent.com/assets/447559/11842806/f9cab7aa-a3fd-11e5-936c-de67b3680471.png)
cc @i-like-robots @alicebartlett

^^ that's supposed to be a screenshot of a link with gibberish content. Not sure why screenshot didn't work

**Comment by i-like-robots** [comment]
Do it.

I thought we had tackled this within Next a while ago as part of the [a11y quick wins](https://github.com/Financial-Times/next/issues/53) but obvs. not =S

**Comment by leggsimon** [comment]
@wheresrhys can you send me that screenshot in slack?

**Comment by wheresrhys** [comment]
I don't have it any more. Essentially it just illustrated that a screen
reader is reading out links within an advert, which we should be
preventing. It's the advert above the header on the home page


On 16 December 2015 at 22:53, Simon Legg <notifications@github.com> wrote:

> @wheresrhys <https://github.com/wheresrhys> can you send me that
> screenshot in slack?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-ads/issues/7#issuecomment-165273919>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by alicebartlett** [comment]
This sounds like a good change to me, @leggsimon and I are going to go over some screen reader stuff this afternoon.

**Comment by leggsimon** [comment]
This has been added to o-ads and will be on the next release.

@wheresrhys @alicebartlett @i-like-robots
