### ISSUE TITLE
o-ads does not initialise with o-autoinit

### ISSUE THREAD

**Issue by antoligy** [Financial-Times/o-ads#8]
[Taken from Slack]

Hey, I'm trying to use O-Ads 2.8.1 via the build service using o-autoinit and it looks like the ad slots are never loaded.  Seems as though the component listens for `o.DOMContentLoaded` on `document.documentElement` versus `document` and so is never instantiated with o-autoinit.  On TheBanker this is worked around by manually dispatching the event, is that the correct way of using the component?  (and if so, does it make sense for this to be described in documentation, as it breaks away from the standard behaviour)?

It seems as though the change was made here https://github.com/Financial-Times/o-ads/commit/1a2478a3a5201753bad602b1d05267dc01a984d8 with the demo being updated here https://github.com/Financial-Times/o-ads/commit/79f731f777a3d3a264627cff27dd4c637d7eb8c8

**Comment by antoligy** [comment]
(Using this demo in SauceLabs IE8, the second div is never shown. https://jsbin.com/nuradi)

**Comment by leggsimon** [comment]
@antoligy Thanks for letting us know. We are in the process of improving our documentation, when I get to there I will work out what is meant to be going on and update the code or the documentation where applicable

**Comment by leggsimon** [comment]
We have updated our documentation to reflect this. Closing

**Comment by antoligy** [comment]
@leggsimon just looking at the revised documentation, it still seems inaccurate
>Note: O-ads does not initialise with o-autoinit like other FT Origami modules. The final o-ads initialisation happens on o.DOMContentLoaded.

Shouldn't this instead reflect that the o.DOMContentLoaded event needs to be dispatched on `document.documentElement` versus `document`?  It might also be worth including a code example for how to instantiate this.

(I'm completely happy to submit a PR on Stash if you agree).

**Comment by VladDubrovskis** [comment]
PRs are always welcome :)

**Comment by VladDubrovskis** [comment]
PRs are always welcome :)
