### ISSUE TITLE
Provide styles for elements that demarcate ads

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-ads#85]
<img width="324" alt="us_election_polls_2016" src="https://cloud.githubusercontent.com/assets/684559/19193326/943f6088-8ca1-11e6-94c5-4c5c07e5f6b7.png">

<img width="367" alt="demagogues_reach_beyond_the_bigots" src="https://cloud.githubusercontent.com/assets/684559/19193514/3796e936-8ca2-11e6-88ac-96b9901ac178.png">

At the moment I think this mainly concerns the hatched/shaded area around the slot at the top of the page.

I would have though this is something we'd want to standardise across all ft.com (including things like Markets Data, IG or whatever). From the users point of view it's good to have a familiar consistent way of show what is and is not an advert.

This could be optional for products that don't want to use the styles or when they don't make sense in a particular slot.

**Comment by adgad** [comment]
Added classes as documented here http://financial-times.github.io/o-ads/docs/developer-guide/display#stylingclasses
