### ISSUE TITLE
Add ads-api support for single page apps (e.g. Web app)

### ISSUE THREAD

**Issue by VladDubrovskis** [Financial-Times/o-ads#95]
Now that we have introduced the support of ads api on o-ads, there is a new use case moving forward.

Currently you can pass the user endpoint, content and concept endpoints, and the library will make a requests to get appropriate data. This work fine in the regular website terms, when each new page is new page request and the library get re-initialised.

However, if you are using a single page app, where there is no page reloads, and you wish to handle cases such as:
Navigating through articles
Section pages
User logs in thus needs to get the targeting data

Currently there is no way to achieve this, or at the very least no clear API to achieve this.

I have create a number of tests to cater for those scenarios here:
https://github.com/Financial-Times/o-ads/tree/expose-the-ads-api-updating-method-for-single-page-apps

In theory if you implement the following methods the tests should just pass:
`getUserTargetingFromServer(endpointURL)`
`getContentTargetingFromServer(endpointURL)`
`getConceptTargetingFromServer(endpointURL)`

Ideally we would move all the AdsAPI related code to a new module that is responsible for all the handling of the data, but as a start hacking it into the `main.js` *could* (not necessarily should) be good to make a start.

**Comment by alexflorisca** [comment]
This work has been done in the form of the `updateContext` function: https://github.com/Financial-Times/o-ads/blob/0d635c7f9e310a404582baaa6bceeafda048388e/main.js#L72
